'use strict';

const path = require('path');
const ui = require('../lib/ui.js');
const fsx = require('../lib/fsx.js');
const paths = require('../lib/paths.js');
const payload = require('../lib/payload.js');
const manifest = require('../lib/manifest.js');
const gitignore = require('../lib/gitignore.js');
const bootstrap = require('../lib/bootstrap.js');
const context = require('../lib/context.js');
const detectLib = require('../lib/detect.js');

function help() {
  ui.out(`${ui.color.bold('gatecraft init')} — install the framework into a project

${ui.color.bold('USAGE')}
  gatecraft init [options]

${ui.color.bold('WHAT IT WRITES')}`);
  ui.table([
    ['.ai/', 'The framework — 35 documents. Hidden, git-ignored.'],
    ['AGENTS.md', 'The bootstrap. Visible, committed. ~40 lines.'],
    ['.gitignore', 'One managed block, removable with `gatecraft uninstall`.'],
  ]);
  ui.out(`
${ui.color.bold('OPTIONS')}`);
  ui.table([
    ['--dir <path>', 'Target directory (default: nearest project root)'],
    ['--share', 'Track .ai/memory/, DECISIONS.md, architecture/ in git'],
    ['--track', 'Track all of .ai/ in git — nothing is ignored'],
    ['--no-bootstrap', 'Do not write AGENTS.md (agents will not find the framework)'],
    ['--no-gitignore', 'Do not touch .gitignore'],
    ['--no-detect', 'Do not pre-fill PROJECT_CONTEXT.md from the detected stack'],
    ['--claude', 'Also write CLAUDE.md pointing at AGENTS.md'],
    ['--cursor', 'Also write .cursor/rules/gatecraft.mdc'],
    ['--copilot', 'Also write .github/copilot-instructions.md'],
    ['--all-agents', 'All of the above tool-specific pointers'],
    ['--force, -f', 'Overwrite an existing install, discarding local edits to framework files'],
    ['--yes, -y', 'Accept defaults without prompting'],
  ]);
  ui.out(`
${ui.color.bold('NOTES')}
  Re-running init on an existing install is refused; use ${ui.color.cyan('gatecraft upgrade')}, which
  preserves every file you have edited. ${ui.color.cyan('--force')} is the escape hatch and it
  does discard your edits to framework documents.
`);
  return 0;
}

// Ignore rules for each visibility mode. The default hides everything, which is what
// makes the framework invisible; --share keeps the parts a team actually needs to
// share in version control; --track ignores nothing.
function ignoreLines(mode) {
  if (mode === 'track') return null;
  if (mode === 'share') {
    return [
      '# The framework itself is machine-generated — reinstall it with `npx gatecraft init`.',
      '.ai/*',
      '.ai/checklists/',
      '.ai/evaluation/',
      '.ai/metrics/',
      '.ai/planning/',
      '.ai/prompts/',
      '.ai/research/',
      '.ai/reviews/',
      '.ai/standards/',
      '.ai/templates/',
      '.ai/workflows/',
      '',
      '# Project knowledge is shared: context, decisions, memory, architecture.',
      '!.ai/PROJECT_CONTEXT.md',
      '!.ai/DECISIONS.md',
      '!.ai/memory/',
      '!.ai/architecture/',
      '!.ai/.gatecraft-manifest.json',
    ];
  }
  return ['.ai/'];
}

function toolPointers(root, flags, version) {
  const written = [];
  const want = (k) => flags['all-agents'] || flags[k];

  const pointer = `# AI agent instructions

This repository runs the AI Engineering Operating System v${version}.

**Read \`AGENTS.md\` at the repository root first, then \`.ai/SYSTEM.md\`.**

\`.ai/\` is hidden and git-ignored but present. Everything you need is there:
the engineering loop, the workflows, the standards, the checklists, and the
project memory. Do not skip it and do not improvise a process of your own.

<sub>Generated by gatecraft. Run \`npx gatecraft upgrade\` to refresh.</sub>
`;

  const targets = [
    ['claude', 'CLAUDE.md'],
    ['cursor', path.join('.cursor', 'rules', 'gatecraft.mdc')],
    ['copilot', path.join('.github', 'copilot-instructions.md')],
  ];

  for (const [flag, rel] of targets) {
    if (!want(flag)) continue;
    const file = fsx.assertInside(root, path.join(root, rel));
    if (fsx.exists(file) && !flags.force) {
      ui.warn(`${rel} already exists — left alone (use --force to replace)`);
      continue;
    }
    // Cursor's .mdc format expects frontmatter to always apply the rule.
    const content =
      flag === 'cursor'
        ? `---\ndescription: AI Engineering Operating System\nalwaysApply: true\n---\n\n${pointer}`
        : pointer;
    fsx.write(file, content);
    written.push(rel);
  }
  return written;
}

async function run({ flags }) {
  const version = paths.frameworkVersion();
  const root = flags.dir ? path.resolve(flags.dir) : paths.findProjectRoot();

  if (!fsx.isDir(root)) throw new Error(`not a directory: ${root}`);

  const p = paths.paths(root);
  const mode = flags.track ? 'track' : flags.share ? 'share' : 'hidden';

  // Refuse to silently reinstall. An init that quietly overwrote a customized
  // install would destroy exactly the work this framework exists to accumulate.
  const existing = manifest.load(root);
  if (existing && !flags.force) {
    ui.warn(`gatecraft v${existing.version} is already installed at ${ui.color.cyan(p.ai)}`);
    ui.out('');
    ui.out(`  ${ui.color.cyan('gatecraft upgrade')}   update the framework, keeping every file you edited`);
    ui.out(`  ${ui.color.cyan('gatecraft status')}    see what is installed and what has drifted`);
    ui.out(`  ${ui.color.cyan('gatecraft init -f')}   reinstall, ${ui.color.red('discarding your edits to framework files')}`);
    return 1;
  }
  if (fsx.isDir(p.ai) && !existing && !flags.force) {
    throw new Error(
      `${p.ai} exists but was not installed by gatecraft (no manifest).\n` +
        `  Move it aside, or run \`gatecraft init --force\` to install over it.`
    );
  }

  ui.step(`Installing gatecraft v${version}`);
  ui.table([['project', root]]);

  // 1. Detect the stack. Read-only, no network, no subprocess except `git remote`.
  const detected = flags.detect === false ? { empty: true, ...detectLib.detect(root) } : detectLib.detect(root);
  if (!detected.empty) ui.table([['detected', detectLib.summary(detected)]]);
  if (detected.agents.length) ui.table([['agent config', detected.agents.join(', ')]]);

  // 2. Copy the payload.
  const result = payload.install(p.ai, { mode: 'fresh' });
  const stats = payload.stats();
  ui.ok(`${ui.color.bold('.ai/')} — ${stats.docs} documents, ${stats.lines.toLocaleString()} lines, ${stats.dirs} directories`);

  // 3. Pre-fill PROJECT_CONTEXT.md so the first thing an agent reads is true.
  if (flags.detect !== false && !detected.empty) {
    const filled = context.prefill(p.ai, detected, root);
    if (filled) ui.ok(`${ui.color.bold('.ai/PROJECT_CONTEXT.md')} — pre-filled ${filled} fields, marked for verification`);
  }

  // 4. Record what we wrote, so upgrades can tell our files from the user's.
  const m = manifest.empty(version);
  m.files = payload.fileMap(p.ai);
  m.mode = mode;
  m.detected = {
    languages: detected.languages,
    frameworks: detected.frameworks,
    at: context.today(),
  };

  // 5. Hide it.
  if (flags.gitignore !== false) {
    const lines = ignoreLines(mode);
    if (lines) {
      const r = gitignore.ensure(root, lines);
      m.gitignore.managed = true;
      m.gitignore.mode = mode;
      if (mode === 'share') ui.ok('.gitignore — framework hidden, project memory shared');
      else ui.ok(`.gitignore — ${r.created ? 'created, ' : ''}.ai/ hidden from git`);
    } else {
      ui.info('.gitignore untouched — all of .ai/ is tracked (--track)');
    }
  } else {
    ui.warn('.gitignore untouched (--no-gitignore) — .ai/ will show up in git status');
  }

  // 6. The bootstrap — the one visible file, and the thing that makes it work.
  if (flags.bootstrap !== false) {
    const b = bootstrap.ensure(root, { version, detected });
    m.bootstrap.managed = true;
    m.bootstrap.hash = fsx.hashFile(b.file);
    const verb = { created: 'created', updated: 'updated', merged: 'updated, your content kept', current: 'already current' }[b.action];
    ui.ok(`${ui.color.bold('AGENTS.md')} — ${verb} ${ui.color.dim('(visible and committed — this is what agents read)')}`);
  } else {
    ui.warn('AGENTS.md not written (--no-bootstrap) — no agent will discover .ai/ on its own');
  }

  // 7. Optional tool-specific pointers.
  const pointers = toolPointers(root, flags, version);
  for (const rel of pointers) ui.ok(`${rel} — pointer written`);
  if (pointers.length) m.pointers = pointers;

  manifest.save(root, m);

  // What to do next. Concrete, in order, and honest about which step matters.
  ui.step('Next');
  ui.out(`  1. ${ui.color.bold('Fill in .ai/PROJECT_CONTEXT.md.')} ${ui.color.dim('This is the step that makes the rest work —')}`);
  ui.out(`     ${ui.color.dim('an agent with a generic framework and no project facts still guesses.')}`);
  ui.out(`  2. ${ui.color.bold('Commit AGENTS.md.')} ${ui.color.dim('Your teammates and their agents need it.')}`);
  ui.out(`  3. ${ui.color.bold('Just give your agent a task, normally.')}`);
  ui.out('');
  // The most common misconception is that a framework this size needs special
  // syntax to invoke. Showing an ordinary sentence is the fastest correction.
  ui.out(`     ${ui.color.dim('"Add rate limiting to the login endpoint."')}`);
  ui.out('');
  ui.out(`     ${ui.color.dim('No special syntax, no flags, no prompt template. Your agent reads')}`);
  ui.out(`     ${ui.color.dim('AGENTS.md, follows it into .ai/, picks the matching workflow, and')}`);
  ui.out(`     ${ui.color.dim('runs the loop. What changes is what comes back, not how you ask.')}`);
  ui.out('');
  ui.out(`  ${ui.color.cyan('gatecraft status')}  ${ui.color.dim('what is installed, and what still needs filling in')}`);
  ui.out(`  ${ui.color.cyan('gatecraft doctor')}  ${ui.color.dim('check the install is sound')}`);
  ui.out('');

  return 0;
}

module.exports = { run, help, ignoreLines };
